=== rgs0042/Lenguages2025-Rafael_Garcia/2ºtrimestre/2ºtrimestre/xsd_explicacion/ejercicios_xml/ej02_05.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tarjeta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="credito">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="numero">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="id" use="required" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="venci" type="xs:string" />
                            <xs:element name="chip" type="xs:string" />
                            <xs:element name="logo" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="creditoatr">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="firma" type="xs:string" />
                            <xs:element name="cvv" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rgs0042/Lenguages2025-Rafael_Garcia/2ºtrimestre/2ºtrimestre/xsd_explicacion/ejercicios_xml/ej02_05.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/css" href="ej02_05.css"?>
<tarjeta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ej02_05.xsd">
    <credito>
        <numero id="n1234">1234567891234567</numero>
        <nombre>Pepe</nombre>
        <venci>99/99/9999</venci>
        <chip>La tarjeta de crédito tiene un chip</chip>
        <logo>Logo</logo>

    </credito>
    <creditoatr>
        <firma>Esto debería de ser una firma</firma>
        <cvv>999</cvv>
    </creditoatr>
</tarjeta>
