=== rgs0042/Lenguages2025-Rafael_Garcia/2ºtrimestre/2ºtrimestre/xsd_explicacion/ejercicios_xml/ej02_04.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tarjeta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="dni">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fotografia" type="xs:string" />
                            <xs:element name="contenido">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="apellidos" type="xs:string" />
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="fechanac" type="xs:string" />
                                        <xs:element name="lugarnac" type="xs:string" />
                                        <xs:element name="sexo" type="xs:string" />
                                        <xs:element name="nacionalidad" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dniatr">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="firma" type="xs:string" />
                            <xs:element name="id">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="id" use="required" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="fechaemi" type="xs:string" />
                            <xs:element name="caducidad" type="xs:string" />
                            <xs:element name="domicilio" type="xs:string" />
                            <xs:element name="texto" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rgs0042/Lenguages2025-Rafael_Garcia/2ºtrimestre/2ºtrimestre/xsd_explicacion/ejercicios_xml/ej02_04.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/css" href="ej02_04.css"?>

<tarjeta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ej02_04.xsd">
    <dni>
        <fotografia>Foto</fotografia>
        <contenido>
            <apellidos>Lucas Lucas</apellidos>
            <nombre>Pepe</nombre>
            
            <fechanac>66/66/6666</fechanac>
            <lugarnac>Allí</lugarnac>
            <sexo>Macho</sexo>
            <nacionalidad>Aquí</nacionalidad>
        </contenido>

    </dni>
    <dniatr>

        <firma>Firma</firma>
        <id id="c123">00000000z</id>
        <fechaemi>99/99/9999</fechaemi>
        <caducidad>88/88/8888</caducidad>
        <domicilio>Aquí y Allí</domicilio>

        <texto>JAJAJAJAJAJJAJJAJAJAJAJAJAJJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJJ</texto>

    </dniatr>
</tarjeta>
