<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/css" href="libros2.css"?> 

<!-- Las lineas de antes son el prologo-->

<!-- esto es el DTD. es decir, la validación-->
<!DOCTYPE biblioteca 

[   <!ENTITY editorial "olkase">
    <!ELEMENT biblioteca (libro+)>
    <!ELEMENT libro (titulo?, portada*, autor+,(resumen | texto))> 
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT portada (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT resumen (#PCDATA)>
    <!ATTLIST libro paginas CDATA #REQUIRED>
    <!ATTLIST portada foto CDATA #REQUIRED>
]>
<!-- y esto el cuerpo del documento-->
<biblioteca>
<libro paginas="235">
    <titulo>El Arbol de la ciencia DE &editorial;</titulo>
    <portada foto="ciencia"></portada>
    <autor>Pío Baroja</autor>
    <resumen>
        El árbol de la ciencia narra la vida de Andrés Hurtado hasta su muerte por suicidio. El tema central del libro es la desorientación existencial del hombre inadaptado y encerrado en un callejón sin salida.
    </resumen>
    
</libro>
<libro paginas="135" >
    <titulo>La Celestina</titulo>
    <portada foto="celestina"></portada>
    <autor>Fernando de Rojas</autor>
    <resumen>
        LA CELESTINA: COMEDIA O TRAGICOMEDIA DE CALISTO Y MELIBEA. Calisto, joven de noble familia, persiguiendo un día un halcón, entra en el jardín de una doncella también noble, Melibea, y queda rendidamente enamorado de ella, pero es rechazado.
    </resumen>
</libro>
<libro paginas="342" >
    <titulo>1984</titulo>
    <portada foto="1984"></portada>
    <autor>George Orwell</autor>
    <resumen>
        1984 de George Orwell es una novela de distopía cuya trama ocurre en Oceanía, un país dominado por un gobierno totalitario que mantiene en constante vigilancia a sus ciudadanos e, incluso, insiste en espiar sus pensamientos para mantener el orden.
    </resumen>
</libro>
<libro paginas="452">
    <titulo>El extranjero</titulo>
    <portada foto="extranjero"></portada>
    <autor>Albert Camus</autor>
    <resumen>
        El extranjero narra las peripecias vitales de Meursault, que comete un crimen en apariencia inmotivado, cuyo juicio desencadena múltiples circunstancias alrededor de la condición humana, la cotidianidad, la culpa, la responsabilidad…
    </resumen>
</libro>


</biblioteca>