=== rgs0042/Lenguages2025-Rafael_Garcia/2ºtrimestre/Explicación clase T10 XML/libros1.dtd
<!ELEMENT libro (titulo, autor+, capitulo)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT capitulo (titulocap , texto)>
    <!ELEMENT titulocap (#PCDATA)>
    <!ELEMENT texto (#PCDATA)>

=== rgs0042/Lenguages2025-Rafael_Garcia/2ºtrimestre/Explicación clase T10 XML/libros1-dtd-externo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="libros1.css"?>

<!DOCTYPE libro SYSTEM "libros1.dtd">

<libro>
    <titulo>Titulo1</titulo>
    <autor>Autor 1</autor>
    <autor>Autor 2</autor>
    <autor>Autor 3</autor>
    <capitulo>
        <titulocap>Capitulo 1</titulocap>
        <texto>Aqui viene un texto mas largo con  un resumen capitulo 1</texto>
    </capitulo>
</libro>
